CREATE TABLE `Admin` (
  `id` INTEGER NOT NULL AUTO_INCREMENT, `name` VARCHAR(120) NOT NULL,
  `email` VARCHAR(191) NOT NULL, `passwordHash` VARCHAR(255) NOT NULL,
  `role` ENUM('SUPER_ADMIN', 'EDITOR') NOT NULL DEFAULT 'EDITOR',
  `isActive` BOOLEAN NOT NULL DEFAULT true, `lastLoginAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), `updatedAt` DATETIME(3) NOT NULL,
  UNIQUE INDEX `Admin_email_key`(`email`), INDEX `Admin_isActive_idx`(`isActive`), PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
